server:
  port: 8082
spring:
  data:
    mongodb:
      host: 10.19.151.197
      port: 27017
      authentication-database: admin
      database: saas_qrcode
      username: bocom
      password: Bocom_123